# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d7b2bd2b7a5f482e8addbeaa7d8aec3348ec7e895bda3f3f0a4446ff95382e560fdb92338492be2332fc0998c8770148b9f8e289abda562e295b6d93a39ce5

test:
  secret_key_base: d3ff75974c14c0ba32563bc90f48900ec4d1e5935e80c95a82f3d4a55b7b1acf237650f1d816f0579035138446854a845bc3dd5bd7b0138a8fe43e96e2ba455e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
